yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name='Имя', max_length=200)
    slug = models.SlugField(verbose_name='Идентификатор', unique=True)
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        help_text='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Сообщество',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Выберите изображение для загрузки'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        on_delete=models.CASCADE,
        related_name='comments',
        help_text='Пост'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments',
        help_text='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True,
        help_text='Дата комментария'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='follower',
        help_text='Пользователи'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following',
        help_text='Автор'
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import get_page_obj


@cache_page(20)
def index(request: HttpRequest) -> HttpResponse:
    post_list = Post.objects.select_related('author', 'group').all()
    context = {
        'page_obj': get_page_obj(request, post_list),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
        'page_obj': get_page_obj(request, post_list),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    user = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(
        author=user).prefetch_related('author', 'group').all()
    if not request.user.is_anonymous:
        following = user.following.filter(user=request.user).exists()
    else:
        following = False

    context = {
        'author': user,
        'page_obj': get_page_obj(request, post_list),
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)

    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user)

    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'is_edit': True,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request: HttpRequest, post_id: int):
    post = get_object_or_404(Post, pk=post_id)

    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment: Comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request: HttpRequest):
    author_list = [follow.author for follow in request.user.follower.all()]

    post_list = Post.objects.select_related(
        'author', 'group').filter(author__in=author_list)
    context = {
        'page_obj': get_page_obj(request, post_list),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request: HttpRequest, username: str):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    is_signed = request.user.follower.filter(author=author).exists()
    if username != request.user.username and not is_signed:
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request: HttpRequest, username: str):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user).filter(author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} 
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}  
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %} 
            Редактируемый пост
          {% else %}
            Новый пост
          {% endif %}               
        </div>
        <div class="card-body">    
          {% include 'includes/errors.html' %}    
          
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {% for field in form %}
              {% include 'includes/form_out.html' %}
            {% endfor %} 
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %} 
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}    

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block content %}
  <h1>Посты авторов</h1>
  {% for post in page_obj %}
    {% include "includes/article.html"%}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}

{% block title %}
  Записки сообщества {{ group.title }}
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description }}
  </p>

  {% for post in page_obj %}
    {% include "includes/article.html"%}
    {% if not forloop.last %}<hr>{% endif %}
  {% empty %}
    <p>Пока ничего не написали</p>
  {% endfor %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% cache 20 index_page %}
    {% for post in page_obj %}
      {% include "includes/article.html"%}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  {% endcache %}
  {% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% block title %}
  Пост {{ post.text|truncatechars:30 }} 
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %} 
          <li class="list-group-item">
            Группа: {{ post.group.title }} 
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: 
          {{ post.author.get_full_name }}  
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{ post.text|linebreaksbr }} </p>
      {% if post.author == user %}
        <p>  
          <a href="{% url 'posts:post_edit' post.pk %}">
            Изменить пост
          </a>
        </p>
      {% endif %}
      {% include "includes/comments.html" %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }} 
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя 
      {{ author.get_full_name }}
    </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>   
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" 
          role="button">
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" 
            role="button">
          Подписаться
        </a>
    {% endif %}  
  </div>
  {% for post in page_obj %}
    {% include "includes/article.html"%}
    {% if not forloop.last %}<hr>{% endif %}  
  {% endfor %}
  {% include "posts/includes/paginator.html" %}    
{% endblock %}